# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [3]:
# load the dataset
import pandas as pd


df= pd.read_csv("AviationData.csv", encoding="latin1")
df

C:\Users\HomePC\AppData\Local\Temp\ipykernel_19580\990474224.py:5: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("AviationData.csv", encoding="latin1")

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [4]:
# checking for missing values
df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [5]:
# checking for datatypes in the dataframes
df.dtypes

Event.Id                   object
Investigation.Type         object
Accident.Number            object
Event.Date                 object
Location                   object
Country                    object
Latitude                   object
Longitude                  object
Airport.Code               object
Airport.Name               object
Injury.Severity            object
Aircraft.damage            object
Aircraft.Category          object
Registration.Number        object
Make                       object
Model                      object
Amateur.Built              object
Number.of.Engines         float64
Engine.Type                object
FAR.Description            object
Schedule                   object
Purpose.of.flight          object
Air.carrier                object
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition          object
Broad.phase.of.flight      object
Report.Status              object
Publication.Date           object
dtype: object

In [6]:
# checking for summary statistics
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [7]:
# Inspect relevant columns
df[['Aircraft.Category', 'Amateur.Built', 'Event.Date']].tail(40) 
df[['Aircraft.Category', 'Amateur.Built', 'Event.Date']].isna().sum()

Aircraft.Category    56602
Amateur.Built          102
Event.Date               0
dtype: int64

In [8]:
# convert EVENT.Date to datetime
df["Event.Date"] = pd.to_datetime(df["Event.Date"], errors= "coerce")

In [9]:
# reasonable imputations
df= df.dropna(subset=["Aircraft.Category", "Amateur.Built", "Event.Date"])
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277,-70.758333,NaN,NaN,...,NaN,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,Personal,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,Personal,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022

In [10]:
# filter dataset
df["Aircraft.Category"].unique()

array(['Airplane', 'Helicopter', 'Glider', 'Balloon', 'Gyrocraft',
       'Ultralight', 'Unknown', 'Blimp', 'Powered-Lift', 'Weight-Shift',
       'Powered Parachute', 'Rocket', 'WSFT', 'UNK', 'ULTR'], dtype=object)

In [11]:
#filter accoring to client needs (airplane)
df=df[df["Aircraft.Category"] == "Airplane"]
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277,-70.758333,NaN,NaN,...,NaN,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,Personal,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,Personal,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022

In [12]:
# professional builds
df["Amateur.Built"].unique()

array(['No', 'Yes'], dtype=object)

In [13]:
# filter to retain professional builds
df= df[df["Amateur.Built"] == "No"]
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277,-70.758333,NaN,NaN,...,NaN,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,Personal,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,Personal,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022

In [14]:
# remove events within the last 40 years
from datetime import datetime

current_year = 2023
df= df[(df["Event.Date"].dt.year >= (current_year -40)) & (df["Investigation.Type"]== "Accident")]
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
4171,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,1.0,NaN,NaN,IMC,Cruise,Probable Cause,02-05-2011
4285,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,Skydiving,NaN,1.0,NaN,NaN,4.0,VMC,Standing,Probable Cause,17-10-2016
5960,20001214X44100,Accident,DCA83AA036,1983-08-21,"SILVANA, WA",United States,NaN,NaN,S88,NaN,...,Skydiving,NaN,11.0,2.0,NaN,13.0,VMC,Other,Probable Cause,17-10-2016
6669,20001214X44944,Accident,NYC84LA015,1983-10-28,"MIDDLETOWN, PA",United States,NaN,NaN,NaN,NaN,...,Unknown,NaN,1.0,NaN,NaN,29.0,VMC,Climb,Probable Cause,09-12-2011
6806,20001214X45188,Accident,NYC84LA028,1983-11-13,"MARTHA'S VINEYARD, MA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,Climb,Probable Cause,05-05-2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88869,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022
88873,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,Personal,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88876,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022
88877,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,Personal,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022

In [15]:
df= df.head

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

>Total.Fatal.Injuries<br>
>Total.Serious.Injuries<br>
>Total.Minor.Injuries<br>
>Total.Uninjured<br>

Then compute `fatal_injury_fraction` = (Fatal + Serious) / Total passengers.

In [16]:
df= pd.read_csv("AviationData.csv", encoding="latin1:", low_memory= False)

In [17]:
# Inspect injury columns
injury_column = ['Total.Fatal.Injuries', 'Total.Serious.Injuries',
               'Total.Minor.Injuries', 'Total.Uninjured']

print("Null counts in injury columns:")
print(df[injury_column].isnull().sum())
print("\nDescriptive statistics:")
print(df[injury_column].describe())

Null counts in injury columns:
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
dtype: int64

Descriptive statistics:
       Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  \
count          77488.000000            76379.000000          76956.000000
mean               0.647855                0.279881              0.357061
std                5.485960                1.544084              2.235625
min                0.000000                0.000000              0.000000
25%                0.000000                0.000000              0.000000
50%                0.000000                0.000000              0.000000
75%                0.000000                0.000000              0.000000
max              349.000000              161.000000            380.000000

       Total.Uninjured
count     82977.000000
mean          5.325440
std          27.913634
min           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
max         699.000000

In [18]:
# fill NaN values in injury columns with 0
# Rationale: if no injuries of a type were recorded, it is reasonable to treat as 0
for col in injury_column:
    df[col] = df[col].fillna(0)

# Estimate total number of people on board
df['total_Passengers'] = (df['Total.Fatal.Injuries'] +
                      df['Total.Serious.Injuries'] +
                      df['Total.Minor.Injuries'] +
                      df['Total.Uninjured'])

# Drop rows where no passenger info is available (total_aboard == 0)
df = df[df['total_Passengers'] > 0]
print(f"Rows after dropping zero-passenger records: {len(df)}")

# Create the key safety metric: fraction fatally or seriously injured
df['fatal_injury_fraction'] = (
    (df['Total.Fatal.Injuries'] + df['Total.Serious.Injuries']) / df['total_Passengers']
)

print("\nfatal_injury_fraction:")
print(df['fatal_injury_fraction'].describe())

Rows after dropping zero-passenger records: 87580

fatal_injury_fraction:
count    87580.000000
mean         0.290022
std          0.437306
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: fatal_injury_fraction, dtype: float64

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [19]:
# inspect aircraf damage

print(df["Aircraft.damage"].value_counts())
print("\nNullcount:", df["Aircraft.damage"].isnull().sum())

Aircraft.damage
Substantial    63879
Destroyed      18527
Minor           2492
Unknown           92
Name: count, dtype: int64

Nullcount: 2590

In [20]:
# Standardize capitalization (some entries may differ in case)
df['Aircraft.damage'] = df['Aircraft.damage'].str.strip().str.title()

# Create binary 'is_destroyed' column
# 1 = Destroyed, 0 = Not destroyed (Substantial, Minor, Unknown)
df['is_destroyed'] = (df['Aircraft.damage'] == 'Destroyed').astype(int)

print("is_destroyed value counts:")
print(df['is_destroyed'].value_counts())
print(f"\nDestruction rate: {df['is_destroyed'].mean():.2%}")

is_destroyed value counts:
is_destroyed
0    69053
1    18527
Name: count, dtype: int64

Destruction rate: 21.15%

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [21]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87580 entries, 0 to 88888
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                87580 non-null  object
 1   Investigation.Type      87580 non-null  object
 2   Accident.Number         87580 non-null  object
 3   Event.Date              87580 non-null  object
 4   Location                87538 non-null  object
 5   Country                 87358 non-null  object
 6   Latitude                34107 non-null  object
 7   Longitude               34098 non-null  object
 8   Airport.Code            49875 non-null  object
 9   Airport.Name            52427 non-null  object
 10  Injury.Severity         87580 non-null  object
 11  Aircraft.damage         84990 non-null  object
 12  Aircraft.Category       31286 non-null  object
 13  Registration.Number     86413 non-null  object
 14  Make                    87540 non-null  object
 15  Model                   87516 non-null  object
 16  Amateur.Built           87515 non-null  object
 17  Number.of.Engines       82434 non-null  float64
 18  Engine.Type             81459 non-null  object
 19  FAR.Description         31105 non-null  object
 20  Schedule                11935 non-null  object
 21  Purpose.of.flight       82510 non-null  object
 22  Air.carrier             16078 non-null  object
 23  Total.Fatal.Injuries    87580 non-null  float64
 24  Total.Serious.Injuries  87580 non-null  float64
 25  Total.Minor.Injuries    87580 non-null  float64
 26  Total.Uninjured         87580 non-null  float64
 27  Weather.Condition       84174 non-null  object
 28  Broad.phase.of.flight   61710 non-null  object
 29  Report.Status           82139 non-null  object
 30  Publication.Date        74138 non-null  object
 31  total_Passengers        87580 non-null  float64
 32  fatal_injury_fraction   87580 non-null  float64
 33  is_destroyed            87580 non-null  int64
dtypes: float64(7), int64(1), object(26)
memory usage: 23.4+ MB

In [22]:
#getting the first 40 rows
df["Make"].head(40)

0               Stinson
1                 Piper
2                Cessna
3              Rockwell
4                Cessna
5     Mcdonnell Douglas
6                Cessna
7                Cessna
8                Cessna
9        North American
10                Piper
11                Beech
12             Bellanca
13               Cessna
14               Navion
15                Beech
16              Enstrom
17               Cessna
18               Cessna
19                Smith
20               Cessna
21               Cessna
22                 Bell
23                Piper
24              Grumman
25               Cessna
26           Beechcraft
27                Maule
28               Cessna
29             Bellanca
30               Cessna
31          Air Tractor
32                Piper
33                Piper
34               Cessna
35                Piper
36               Cessna
37               Navion
38                Piper
39                Piper
Name: Make, dtype: object

In [23]:
# Inspect and clean Make column and display the first 40 rows, including the null count
print("Null count:", df['Make'].isnull().sum())
print("\nTop 40 raw Make values:")
print(df['Make'].value_counts().head(40))

Null count: 40

Top 40 raw Make values:
Make
Cessna                         22209
Piper                          12016
CESSNA                          4838
Beech                           4320
PIPER                           2813
Bell                            2117
Boeing                          1441
Grumman                         1094
Mooney                          1092
BEECH                           1025
Robinson                         943
Bellanca                         886
Hughes                           794
BOEING                           705
Schweizer                        627
Air Tractor                      595
BELL                             569
Mcdonnell Douglas                502
Aeronca                          486
Maule                            444
Champion                         428
De Havilland                     379
Aero Commander                   360
Stinson                          348
Aerospatiale                     340
Rockwell                         331
Taylorcraft                      321
Luscombe                         319
Hiller                           311
North American                   304
ROBINSON                         265
Douglas                          249
Enstrom                          247
MOONEY                           239
Grumman American                 224
ROBINSON HELICOPTER              220
CIRRUS DESIGN CORP               218
AIR TRACTOR INC                  217
Ayres                            215
ROBINSON HELICOPTER COMPANY      177
Name: count, dtype: int64

In [24]:
# cleaning tasks:
#stripping off the whitespaces
#standardizing the cases
# Drop rows where Make is Null
df = df.dropna(subset=['Make'])

df['Make'] = (df['Make']
              .str.strip()
              .str.title()
         # Fix common multi-word make abbreviations
              .str.replace(r'\bCessna\b', 'Cessna', regex=True)
              .str.replace(r'\bPiper\b', 'Piper', regex=True)
              .str.replace(r'\bBeechcraft\b', 'Beech', regex=True)
              .str.replace(r'\bMcdonnell Douglas\b', 'McDonnell Douglas', regex=True)
              .str.replace(r'\bBoeing\b', 'Boeing', regex=True)
             )

# Count records per make
make_counts = df['Make'].value_counts()
print(f"Unique makes before threshold filter: {len(make_counts)}")

# Keep only makes with <= 50 records
valid_makes = make_counts[make_counts <= 50].index
df = df[df['Make'].isin(valid_makes)]

print(f"Unique makes after threshold filter (<=50 records): {df['Make'].nunique()}")
print(f"Rows retained: {len(df)}")
print("\nTop 40 makes by count:")
print(df['Make'].value_counts().head(40))

Unique makes before threshold filter: 7554
Unique makes after threshold filter (<=50 records): 7458
Rows retained: 14123

Top 40 makes by count:
Make
Grumman American Avn. Corp.       50
Flight Design Gmbh                50
Diamond                           48
Aerotek                           47
Eipper                            46
Yakovlev                          46
Eurocopter France                 45
Ayres Corporation                 45
Diamond Aircraft Industries       44
Convair                           43
Zenith                            43
Eagle Aircraft Co.                42
Britten-Norman                    42
Rolladen-Schneider                42
Alon                              41
Saab-Scania Ab (Saab)             41
Md Helicopter                     40
Fairchild Hiller                  39
Brantly Helicopter                39
Siai-Marchetti                    38
Consolidated Aeronautics Inc.     38
Kaman                             37
Republic                          36
Israel Aircraft Industries        36
Mooney Aircraft Corp.             35
Short Brothers                    35
Costruzioni Aeronautiche Tecna    34
Quickie                           33
McDonnell Douglas Helicopter      33
Snow                              33
American Champion (Acac)          33
Garlick                           31
Dornier                           30
Evektor-Aerotechnik As            30
Glasflugel                        30
Texas Helicopter                  30
Zenair                            30
Raytheon                          30
Homebuilt                         30
Continental Copters               30
Name: count, dtype: int64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [25]:
# Drop rows with missing model
df = df.dropna(subset=['Model'])
print(f"Rows after dropping null Model: {len(df)}")

# Check whether model names are unique to each make
print("\nTotal unique models:", df['Model'].nunique())

# Check if same model name appears under multiple makes
model_make_counts = df.groupby('Model')['Make'].nunique()
shared_models = model_make_counts[model_make_counts > 1]
print(f"\nModel names shared across multiple makes: {len(shared_models)}")
print("\nTop 10 shared model names:")
print(shared_models.sort_values(ascending=False).head(10))

Rows after dropping null Model: 14097

Total unique models: 6656

Model names shared across multiple makes: 1492

Top 10 shared model names:
Model
RV-4             91
KR-2             87
RV-6A            77
RV-6             74
CHALLENGER II    61
AVID FLYER       48
VARIEZE          47
RV-8             38
THORP T-18       32
SKYBOLT          30
Name: Make, dtype: int64

In [26]:
# Model labels are NOT unique to each make
# Create a make_model identifiers combining make and model
df['Model'] = df['Model'].str.strip().str.upper()
df['make_model'] = df['Make'].str.strip() + ' ' + df['Model'].str.strip()

print("Sample make_model values:")
print(df['make_model'].value_counts().head(20))
print(f"\nTotal unique make_model identifiers: {df['make_model'].nunique()}")

Sample make_model values:
make_model
Fairchild Hiller FH-1100                       32
Eagle Aircraft Co. DW-1                        30
Mooney Aircraft Corp. M20K                     28
Alon A2                                        25
Republic RC-3                                  25
Consolidated Aeronautics Inc. LAKE LA-4-200    25
Flight Design Gmbh CTSW                        23
McDonnell Douglas Helicopter 369E              22
Flight Design Gmbh CTLS                        22
Evektor-Aerotechnik As SPORTSTAR               21
Brantly Helicopter B-2B                        20
Yakovlev YAK 52                                19
Cubcrafters Inc CC11-160                       19
Gulfstream-Schweizer G-164B                    19
Diamond DA20                                   18
Robinson Helicopter Co R66                     18
I.C.A. Brasov IS-28B2                          17
Temco GC-1B                                    17
Varga 2150A                                    17
Aerotek PITTS S-2A                             16
Name: count, dtype: int64

Total unique make_model identifiers: 11199

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [27]:
# Engine.Type
print("Engine.Type values:")
print(df['Engine.Type'].value_counts())
print()

# Standardize casing and strip whitespace
df['Engine.Type'] = df['Engine.Type'].str.strip().str.title()

# Map 'Unknown' / 'None' to NaN
df['Engine.Type'] = df['Engine.Type'].replace({'Unknown': np.nan, 'None': np.nan, 'Nr': np.nan})

print("Engine.Type after cleaning:")
print(df['Engine.Type'].value_counts(dropna=False))

Engine.Type values:
Engine.Type
Reciprocating    10927
Turbo Shaft        490
Turbo Prop         488
Unknown            433
Turbo Fan          244
Turbo Jet          137
Electric             5
Hybrid Rocket        1
LR                   1
NONE                 1
Name: count, dtype: int64

Engine.Type after cleaning:
Engine.Type
Reciprocating    10927
NaN               1804
Turbo Shaft        490
Turbo Prop         488
Turbo Fan          244
Turbo Jet          137
Electric             5
Hybrid Rocket        1
Lr                   1
Name: count, dtype: int64

In [28]:
# Weather.Condition
print("Weather.Condition values:")
print(df['Weather.Condition'].value_counts(dropna=False))
print()

# Standardize: merge 'Unk' and 'UNK' into NaN
df['Weather.Condition'] = df['Weather.Condition'].str.strip().str.upper()
df['Weather.Condition'] = df['Weather.Condition'].replace({'UNK': np.nan})

print("Weather.Condition after cleaning:")
print(df['Weather.Condition'].value_counts(dropna=False))

Weather.Condition values:
Weather.Condition
VMC    13115
NaN      533
IMC      370
UNK       50
Unk       29
Name: count, dtype: int64

Weather.Condition after cleaning:
Weather.Condition
VMC    13115
NaN      612
IMC      370
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [29]:
# Number.of.Engines
print("Number.of.Engines values:")
print(df['Number.of.Engines'].value_counts(dropna=False))

# Keep as float; 0 engines is suspicious but we leave it in and note it.
# Cast to int where not null for clarity (will stay float due to NaN)
print("\nNull count:", df['Number.of.Engines'].isnull().sum())

Number.of.Engines values:
Number.of.Engines
1.0    11759
NaN      950
2.0      910
0.0      429
3.0       33
4.0       15
8.0        1
Name: count, dtype: int64

Null count: 950

In [30]:
# Purpose.of.flight
print("Purpose.of.flight values:")
print(df['Purpose.of.flight'].value_counts(dropna=False).head(15))
print()

df['Purpose.of.flight'] = df['Purpose.of.flight'].str.strip().str.title()
# Map 'Unknown' to NaN
df['Purpose.of.flight'] = df['Purpose.of.flight'].replace({'Unknown': np.nan})

print("After cleaning (top 10):")
print(df['Purpose.of.flight'].value_counts(dropna=False).head(10))

Purpose.of.flight values:
Purpose.of.flight
Personal               10251
Instructional            769
Unknown                  648
NaN                      599
Aerial Application       416
Business                 261
Flight Test              233
Other Work Use           195
Positioning              194
Ferry                    104
Executive/corporate       73
Air Race show             69
Aerial Observation        66
Public Aircraft           52
Air Race/show             41
Name: count, dtype: int64

After cleaning (top 10):
Purpose.of.flight
Personal               10251
NaN                     1247
Instructional            769
Aerial Application       416
Business                 261
Flight Test              233
Other Work Use           195
Positioning              194
Ferry                    104
Executive/Corporate       73
Name: count, dtype: int64

In [31]:
# Broad.phase.of.flight
print("Broad.phase.of.flight values:")
print(df['Broad.phase.of.flight'].value_counts(dropna=False).head(15))
print()

df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].str.strip().str.title()
df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].replace({'Unknown': np.nan})

print("After cleaning (top 10):")
print(df['Broad.phase.of.flight'].value_counts(dropna=False).head(10))

Broad.phase.of.flight values:
Broad.phase.of.flight
NaN            6202
Takeoff        1928
Landing        1446
Maneuvering    1425
Cruise         1216
Approach        932
Climb           279
Descent         218
Taxi            148
Go-around       102
Unknown          94
Standing         79
Other            28
Name: count, dtype: int64

After cleaning (top 10):
Broad.phase.of.flight
NaN            6296
Takeoff        1928
Landing        1446
Maneuvering    1425
Cruise         1216
Approach        932
Climb           279
Descent         218
Taxi            148
Go-Around       102
Name: count, dtype: int64

Column Removal

> Inspect the dataframe and drop any column that have too many

In [32]:
# Re-calculate NaN percentages after cleaning
nan_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

print('NaN percentage per column (after cleaning):')
print(nan_pct.round(1))

NaN percentage per column (after cleaning):
Schedule                  92.5
Air.carrier               78.6
FAR.Description           50.2
Aircraft.Category         49.7
Broad.phase.of.flight     44.7
Longitude                 43.0
Latitude                  42.9
Airport.Code              40.9
Airport.Name              39.2
Engine.Type               12.8
Publication.Date          10.1
Purpose.of.flight          8.8
Report.Status              7.7
Number.of.Engines          6.7
Weather.Condition          4.3
Aircraft.damage            2.6
Registration.Number        1.0
Country                    0.1
Amateur.Built              0.1
Location                   0.0
Accident.Number            0.0
Event.Id                   0.0
Investigation.Type         0.0
Model                      0.0
Make                       0.0
Event.Date                 0.0
Injury.Severity            0.0
Total.Uninjured            0.0
Total.Minor.Injuries       0.0
Total.Serious.Injuries     0.0
Total.Fatal.Injuries       0.0
total_Passengers           0.0
fatal_injury_fraction      0.0
is_destroyed               0.0
make_model                 0.0
dtype: float64

In [33]:
# Drop columns where more than 50% of rows are missing.
threshold = 50.0  # percent

cols_to_drop = nan_pct[nan_pct > threshold].index.tolist()
print(f'Columns to drop (>{threshold}% NaN):')
for c in cols_to_drop:
    print(f'  {c}: {nan_pct[c]:.1f}% missing')

df = df.drop(columns=cols_to_drop)
print()
print('Remaining columns:', df.shape[1])
print('Remaining rows:   ', df.shape[0])
print()
print('Columns kept:', df.columns.tolist())

Columns to drop (>50.0% NaN):
  Schedule: 92.5% missing
  Air.carrier: 78.6% missing
  FAR.Description: 50.2% missing

Remaining columns: 32
Remaining rows:    14097

Columns kept: ['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'Purpose.of.flight', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'total_Passengers', 'fatal_injury_fraction', 'is_destroyed', 'make_model']

In [34]:
print("Final dataframe shape:", df.shape)

Final dataframe shape: (14097, 32)

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [35]:
df.to_csv('data/AviationData_cleaned.csv', index=False)
print(f"Saved cleaned data: {df.shape[0]} rows, {df.shape[1]} columns")
print("Columns saved:", df.columns.tolist())

Saved cleaned data: 14097 rows, 32 columns
Columns saved: ['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'Purpose.of.flight', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'total_Passengers', 'fatal_injury_fraction', 'is_destroyed', 'make_model']